apiVersion: v1
kind: Service
metadata:
  name: order-consumer-service
spec:
  type: ClusterIP
  selector:
    component: order-consumer
  ports:
    - port: 5000
      name: http
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-consumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: order-consumer
  template:
    metadata:
      labels:
        component: order-consumer
    spec:
      containers:
        - name: order-consumer
          image: order:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "300Mi" #"1Gi"
              # cpu: "1"
            requests:
              memory: "300Mi" #"1Gi"
              # cpu: "1"
          command: ["gunicorn"]
          args: ["-b", "0.0.0.0:5000", "--log-level", "debug", "consumer:app"]
          ports:
            - containerPort: 5000
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: USER_SERVICE_URL
              value: "user-service"
            - name: STOCK_SERVICE_URL
              value: "stock-service"
            - name: REDIS_HOST
              value: redis-master
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_PASSWORD
              value: "redis"
            - name: REDIS_DB
              value: "0"
            - name: POSTGRES_HOST
              value: order-db
            - name: POSTGRES_PASSWORD
              value: "secret"
            - name: POSTGRES_USER
              value: "username"
            - name: POSTGRES_DB
              value: "database"
            - name: POSTGRES_PORT
              value: '5432'  
           