fullnameOverride: central-db

auth:
  username: "username"
  password: "secret"
  database: "database"

primary:
  initdb:
    scripts: 
      db-schema.sql: |-
        CREATE TYPE items AS (item_id int, amount int, unit_price NUMERIC(255, 2));
        CREATE TABLE IF NOT EXISTS payment (user_id SERIAL, credit NUMERIC(255, 2) CHECK (credit >= 0), PRIMARY KEY (user_id));
        CREATE TABLE IF NOT EXISTS stock (item_id SERIAL, stock int NOT NULL, unit_price NUMERIC(255, 2) CHECK (unit_price >= 0), PRIMARY KEY (item_id));
        CREATE TABLE IF NOT EXISTS order_table (order_id SERIAL, user_id int NOT NULL REFERENCES payment, paid boolean NOT NULL, items items[] NOT NULL, total_price NUMERIC(255, 2) CHECK (total_price >= 0), PRIMARY KEY (order_id));
    user: "username"
    password: "secret"